# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:

#    allowed_methods_listener:  true
    routing_loader:
        default_format: json
        include_format: false
    body_listener: true
    format_listener:
        rules:
            - { path: ^/, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
    param_fetcher_listener:  true
    access_denied_listener:
        json: true
    view:
        view_response_listener: 'force'
        formats:
          json: true
          jsonld: true
#    exception:
#        enabled: true
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.

