<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.yqiw9qO' shared service.

return $this->privates['.service_locator.yqiw9qO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'userMessageService' => ['privates', 'App\\Service\\UserMessageService', 'getUserMessageServiceService.php', true],
    'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService.php', true],
], [
    'userMessageService' => 'App\\Service\\UserMessageService',
    'userRepository' => 'App\\Repository\\UserRepository',
]);
