<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.SavWPcx' shared service.

return $this->privates['.service_locator.SavWPcx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService.php', true],
    'experience' => ['privates', '.errored..service_locator.SavWPcx.App\\Entity\\Experience', NULL, 'Cannot autowire service ".service_locator.SavWPcx": it references class "App\\Entity\\Experience" but no such service exists.'],
    'experienceLikeRepository' => ['privates', 'App\\Repository\\ExperienceLikeRepository', 'getExperienceLikeRepositoryService.php', true],
], [
    'entityManager' => '?',
    'experience' => 'App\\Entity\\Experience',
    'experienceLikeRepository' => 'App\\Repository\\ExperienceLikeRepository',
]);
