<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.qP90MlR' shared service.

return $this->privates['.service_locator.qP90MlR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService.php', true],
    'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService.php', true],
    'userMessageRepository' => ['privates', 'App\\Repository\\UserMessageRepository', 'getUserMessageRepositoryService.php', true],
    'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService.php', true],
], [
    'entityManager' => '?',
    'mailer' => '?',
    'userMessageRepository' => 'App\\Repository\\UserMessageRepository',
    'userRepository' => 'App\\Repository\\UserRepository',
]);
