<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.gkd5S5j' shared service.

return $this->privates['.service_locator.gkd5S5j'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'article' => ['privates', '.errored..service_locator.gkd5S5j.App\\Entity\\Article', NULL, 'Cannot autowire service ".service_locator.gkd5S5j": it references class "App\\Entity\\Article" but no such service exists.'],
    'articleLikeRepository' => ['privates', 'App\\Repository\\ArticleLikeRepository', 'getArticleLikeRepositoryService.php', true],
    'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService.php', true],
], [
    'article' => 'App\\Entity\\Article',
    'articleLikeRepository' => 'App\\Repository\\ArticleLikeRepository',
    'entityManager' => '?',
]);
