<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.sU1Nfqz' shared service.

return $this->privates['.service_locator.sU1Nfqz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'articleRepository' => ['privates', 'App\\Repository\\ArticleRepository', 'getArticleRepositoryService.php', true],
    'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService.php', true],
], [
    'articleRepository' => 'App\\Repository\\ArticleRepository',
    'entityManager' => '?',
]);
