<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.zW5udi7' shared service.

return $this->privates['.service_locator.zW5udi7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'userMessageRepository' => ['privates', 'App\\Repository\\UserMessageRepository', 'getUserMessageRepositoryService.php', true],
    'userMessageService' => ['privates', 'App\\Service\\UserMessageService', 'getUserMessageServiceService.php', true],
    'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService.php', true],
], [
    'userMessageRepository' => 'App\\Repository\\UserMessageRepository',
    'userMessageService' => 'App\\Service\\UserMessageService',
    'userRepository' => 'App\\Repository\\UserRepository',
]);
