<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\ApiRest\ContactController' shared autowired service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\framework-bundle\\Controller\\ControllerTrait.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\framework-bundle\\Controller\\AbstractController.php';
include_once $this->targetDirs[3].'\\vendor\\friendsofsymfony\\rest-bundle\\Controller\\ControllerTrait.php';
include_once $this->targetDirs[3].'\\vendor\\friendsofsymfony\\rest-bundle\\Controller\\AbstractFOSRestController.php';
include_once $this->targetDirs[3].'\\src\\Controller\\ApiRest\\ContactController.php';
include_once $this->targetDirs[3].'\\src\\Service\\ContactService.php';

$a = ($this->privates['mailer.mailer'] ?? $this->load('getMailer_MailerService.php'));

$this->services['App\\Controller\\ApiRest\\ContactController'] = $instance = new \App\Controller\ApiRest\ContactController(new \App\Service\ContactService(($this->privates['App\\Repository\\ContactRepository'] ?? $this->load('getContactRepositoryService.php')), $a), $a);

$instance->setContainer(($this->privates['.service_locator.plo71B4'] ?? $this->load('get_ServiceLocator_Plo71B4Service.php'))->withContext('App\\Controller\\ApiRest\\ContactController', $this));

return $instance;
