<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\ApiRest\ImportExcelFileController' shared autowired service.

include_once $this->targetDirs[3].'\\src\\Controller\\ApiRest\\ImportExcelFileController.php';

return $this->services['App\\Controller\\ApiRest\\ImportExcelFileController'] = new \App\Controller\ApiRest\ImportExcelFileController();
