<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mailer.mailer' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\mailer\\MailerInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\mailer\\Mailer.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\mailer\\Transport.php';

return $this->privates['mailer.mailer'] = new \Symfony\Component\Mailer\Mailer(\Symfony\Component\Mailer\Transport::fromDsn($this->getEnv('MAILER_DSN'), ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()), NULL, ($this->privates['monolog.logger'] ?? $this->getMonolog_LoggerService())), NULL);
