<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Service\MaterialService' shared autowired service.

include_once $this->targetDirs[3].'\\src\\Service\\MaterialService.php';

return $this->privates['App\\Service\\MaterialService'] = new \App\Service\MaterialService(($this->privates['App\\Repository\\MaterialRepository'] ?? $this->load('getMaterialRepositoryService.php')));
