<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Service\UserMessageService' shared autowired service.

include_once $this->targetDirs[3].'\\src\\Service\\UserMessageService.php';

return $this->privates['App\\Service\\UserMessageService'] = new \App\Service\UserMessageService(($this->privates['App\\Repository\\UserMessageRepository'] ?? $this->load('getUserMessageRepositoryService.php')), ($this->services['doctrine.orm.default_entity_manager'] ?? $this->load('getDoctrine_Orm_DefaultEntityManagerService.php')));
