#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_login_check:
  path: /api/login_check
api_logout:
  path: /logout
api:
  prefix: /api
  resource: '../src/Controller/ApiRest'