<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20201203214817 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'postgresql', 'Migration can only be executed safely on \'postgresql\'.');

        $this->addSql('CREATE SEQUENCE addresses_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE addresses (id INT NOT NULL, region_code VARCHAR(3) DEFAULT NULL, region_name VARCHAR(255) DEFAULT NULL, department_number VARCHAR(3) DEFAULT NULL, department_name VARCHAR(255) DEFAULT NULL, city VARCHAR(255) DEFAULT NULL, zip_code VARCHAR(5) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('ALTER TABLE article DROP trial543');
        $this->addSql('ALTER TABLE article ALTER id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN article.id IS NULL');
        $this->addSql('COMMENT ON COLUMN article.user_id IS NULL');
        $this->addSql('COMMENT ON COLUMN article.title IS NULL');
        $this->addSql('COMMENT ON COLUMN article.content IS NULL');
        $this->addSql('COMMENT ON COLUMN article.published_at IS NULL');
        $this->addSql('COMMENT ON COLUMN article.filename IS NULL');
        $this->addSql('COMMENT ON COLUMN article.updated_at IS NULL');
        $this->addSql('ALTER TABLE article_like DROP trial559');
        $this->addSql('ALTER TABLE article_like ALTER id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN article_like.id IS NULL');
        $this->addSql('COMMENT ON COLUMN article_like.article_id IS NULL');
        $this->addSql('COMMENT ON COLUMN article_like.user_id IS NULL');
        $this->addSql('ALTER TABLE borrow_material DROP trial559');
        $this->addSql('ALTER TABLE borrow_material ALTER id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN borrow_material.id IS NULL');
        $this->addSql('COMMENT ON COLUMN borrow_material.id_borrower_id IS NULL');
        $this->addSql('COMMENT ON COLUMN borrow_material.id_lender_id IS NULL');
        $this->addSql('COMMENT ON COLUMN borrow_material.material_id IS NULL');
        $this->addSql('COMMENT ON COLUMN borrow_material.user_id IS NULL');
        $this->addSql('ALTER TABLE comment_article DROP trial562');
        $this->addSql('ALTER TABLE comment_article ALTER id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN comment_article.id IS NULL');
        $this->addSql('COMMENT ON COLUMN comment_article.article_id IS NULL');
        $this->addSql('COMMENT ON COLUMN comment_article.author_name_id IS NULL');
        $this->addSql('COMMENT ON COLUMN comment_article.comment_content IS NULL');
        $this->addSql('COMMENT ON COLUMN comment_article.commented_at IS NULL');
        $this->addSql('ALTER TABLE comment_experience DROP trial565');
        $this->addSql('ALTER TABLE comment_experience ALTER id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN comment_experience.id IS NULL');
        $this->addSql('COMMENT ON COLUMN comment_experience.author_name_id IS NULL');
        $this->addSql('COMMENT ON COLUMN comment_experience.experience_id IS NULL');
        $this->addSql('COMMENT ON COLUMN comment_experience.comment_content IS NULL');
        $this->addSql('COMMENT ON COLUMN comment_experience.commented_at IS NULL');
        $this->addSql('ALTER TABLE contact DROP trial565');
        $this->addSql('ALTER TABLE contact ALTER id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN contact.id IS NULL');
        $this->addSql('COMMENT ON COLUMN contact.first_name IS NULL');
        $this->addSql('COMMENT ON COLUMN contact.last_name IS NULL');
        $this->addSql('COMMENT ON COLUMN contact.message IS NULL');
        $this->addSql('COMMENT ON COLUMN contact.email IS NULL');
        $this->addSql('COMMENT ON COLUMN contact.subject IS NULL');
        $this->addSql('ALTER TABLE experience DROP trial569');
        $this->addSql('ALTER TABLE experience ALTER id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN experience.id IS NULL');
        $this->addSql('COMMENT ON COLUMN experience.user_id IS NULL');
        $this->addSql('COMMENT ON COLUMN experience.title IS NULL');
        $this->addSql('COMMENT ON COLUMN experience.content IS NULL');
        $this->addSql('COMMENT ON COLUMN experience.published_at IS NULL');
        $this->addSql('COMMENT ON COLUMN experience.filename IS NULL');
        $this->addSql('COMMENT ON COLUMN experience.updated_at IS NULL');
        $this->addSql('ALTER TABLE experience_like DROP trial572');
        $this->addSql('ALTER TABLE experience_like ALTER id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN experience_like.id IS NULL');
        $this->addSql('COMMENT ON COLUMN experience_like.experience_id IS NULL');
        $this->addSql('COMMENT ON COLUMN experience_like.user_id IS NULL');
        $this->addSql('ALTER TABLE material DROP trial572');
        $this->addSql('ALTER TABLE material ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE material ALTER availability TYPE BOOLEAN');
        $this->addSql('ALTER TABLE material ALTER availability SET DEFAULT \'false\'');
        $this->addSql('COMMENT ON COLUMN material.id IS NULL');
        $this->addSql('COMMENT ON COLUMN material.user_id IS NULL');
        $this->addSql('COMMENT ON COLUMN material.name IS NULL');
        $this->addSql('COMMENT ON COLUMN material.description IS NULL');
        $this->addSql('COMMENT ON COLUMN material.availability IS NULL');
        $this->addSql('COMMENT ON COLUMN material.borrowed_date IS NULL');
        $this->addSql('COMMENT ON COLUMN material.return_date IS NULL');
        $this->addSql('COMMENT ON COLUMN material.filename IS NULL');
        $this->addSql('COMMENT ON COLUMN material.updated_at IS NULL');
        $this->addSql('COMMENT ON COLUMN material.created_on IS NULL');
        $this->addSql('ALTER TABLE material_borrower_message DROP trial575');
        $this->addSql('ALTER TABLE material_borrower_message ALTER id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN material_borrower_message.id IS NULL');
        $this->addSql('COMMENT ON COLUMN material_borrower_message.sender_message_id_id IS NULL');
        $this->addSql('COMMENT ON COLUMN material_borrower_message.receiver_message_id_id IS NULL');
        $this->addSql('COMMENT ON COLUMN material_borrower_message.user_id IS NULL');
        $this->addSql('COMMENT ON COLUMN material_borrower_message.message IS NULL');
        $this->addSql('COMMENT ON COLUMN material_borrower_message.send_at IS NULL');
        $this->addSql('ALTER TABLE "user" DROP trial578');
        $this->addSql('ALTER TABLE "user" ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE "user" ALTER roles TYPE TEXT');
        $this->addSql('ALTER TABLE "user" ALTER roles DROP DEFAULT');
        $this->addSql('ALTER TABLE "user" ALTER user_connected TYPE BOOLEAN');
        $this->addSql('ALTER TABLE "user" ALTER user_connected DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN "user".id IS NULL');
        $this->addSql('COMMENT ON COLUMN "user".first_name IS NULL');
        $this->addSql('COMMENT ON COLUMN "user".last_name IS NULL');
        $this->addSql('COMMENT ON COLUMN "user".username IS NULL');
        $this->addSql('COMMENT ON COLUMN "user".email IS NULL');
        $this->addSql('COMMENT ON COLUMN "user".password IS NULL');
        $this->addSql('COMMENT ON COLUMN "user".telephone IS NULL');
        $this->addSql('COMMENT ON COLUMN "user".city IS NULL');
        $this->addSql('COMMENT ON COLUMN "user".zip_code IS NULL');
        $this->addSql('COMMENT ON COLUMN "user".roles IS \'(DC2Type:simple_array)\'');
        $this->addSql('COMMENT ON COLUMN "user".user_connected IS NULL');
        $this->addSql('COMMENT ON COLUMN "user".created_at IS NULL');
        $this->addSql('COMMENT ON COLUMN "user".last_login_at IS NULL');
        $this->addSql('ALTER TABLE user_user_type DROP trial585');
        $this->addSql('COMMENT ON COLUMN user_user_type.user_id IS NULL');
        $this->addSql('COMMENT ON COLUMN user_user_type.user_type_id IS NULL');
        $this->addSql('ALTER TABLE user_message DROP trial582');
        $this->addSql('ALTER TABLE user_message ALTER id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN user_message.id IS NULL');
        $this->addSql('COMMENT ON COLUMN user_message.user_id IS NULL');
        $this->addSql('COMMENT ON COLUMN user_message.id_message_sender_id IS NULL');
        $this->addSql('COMMENT ON COLUMN user_message.id_message_receiver_id IS NULL');
        $this->addSql('COMMENT ON COLUMN user_message.message IS NULL');
        $this->addSql('COMMENT ON COLUMN user_message.send_at IS NULL');
        $this->addSql('ALTER TABLE user_profile DROP trial582');
        $this->addSql('ALTER TABLE user_profile ALTER id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN user_profile.id IS NULL');
        $this->addSql('COMMENT ON COLUMN user_profile.user_id IS NULL');
        $this->addSql('COMMENT ON COLUMN user_profile.content_about IS NULL');
        $this->addSql('COMMENT ON COLUMN user_profile.content_aspiration IS NULL');
        $this->addSql('COMMENT ON COLUMN user_profile.hobby IS NULL');
        $this->addSql('COMMENT ON COLUMN user_profile.created_on IS NULL');
        $this->addSql('COMMENT ON COLUMN user_profile.filename IS NULL');
        $this->addSql('COMMENT ON COLUMN user_profile.updated_at IS NULL');
        $this->addSql('ALTER TABLE user_type DROP trial585');
        $this->addSql('ALTER TABLE user_type ALTER id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN user_type.id IS NULL');
        $this->addSql('COMMENT ON COLUMN user_type.name IS NULL');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'postgresql', 'Migration can only be executed safely on \'postgresql\'.');

        $this->addSql('CREATE SCHEMA public');
        $this->addSql('DROP SEQUENCE addresses_id_seq CASCADE');
        $this->addSql('DROP TABLE addresses');
        $this->addSql('ALTER TABLE comment_article ADD trial562 CHAR(1) DEFAULT NULL');
        $this->addSql('CREATE SEQUENCE comment_article_id_seq');
        $this->addSql('SELECT setval(\'comment_article_id_seq\', (SELECT MAX(id) FROM comment_article))');
        $this->addSql('ALTER TABLE comment_article ALTER id SET DEFAULT nextval(\'comment_article_id_seq\')');
        $this->addSql('COMMENT ON COLUMN comment_article.trial562 IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN comment_article.id IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN comment_article.author_name_id IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN comment_article.article_id IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN comment_article.comment_content IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN comment_article.commented_at IS \'TRIAL\'');
        $this->addSql('ALTER TABLE user_profile ADD trial582 CHAR(1) DEFAULT NULL');
        $this->addSql('CREATE SEQUENCE user_profile_id_seq');
        $this->addSql('SELECT setval(\'user_profile_id_seq\', (SELECT MAX(id) FROM user_profile))');
        $this->addSql('ALTER TABLE user_profile ALTER id SET DEFAULT nextval(\'user_profile_id_seq\')');
        $this->addSql('COMMENT ON COLUMN user_profile.trial582 IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN user_profile.id IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN user_profile.user_id IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN user_profile.content_about IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN user_profile.content_aspiration IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN user_profile.hobby IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN user_profile.filename IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN user_profile.created_on IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN user_profile.updated_at IS \'TRIAL\'');
        $this->addSql('ALTER TABLE user_type ADD trial585 CHAR(1) DEFAULT NULL');
        $this->addSql('CREATE SEQUENCE user_type_id_seq');
        $this->addSql('SELECT setval(\'user_type_id_seq\', (SELECT MAX(id) FROM user_type))');
        $this->addSql('ALTER TABLE user_type ALTER id SET DEFAULT nextval(\'user_type_id_seq\')');
        $this->addSql('COMMENT ON COLUMN user_type.trial585 IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN user_type.id IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN user_type.name IS \'TRIAL\'');
        $this->addSql('ALTER TABLE article_like ADD trial559 CHAR(1) DEFAULT NULL');
        $this->addSql('CREATE SEQUENCE article_like_id_seq');
        $this->addSql('SELECT setval(\'article_like_id_seq\', (SELECT MAX(id) FROM article_like))');
        $this->addSql('ALTER TABLE article_like ALTER id SET DEFAULT nextval(\'article_like_id_seq\')');
        $this->addSql('COMMENT ON COLUMN article_like.trial559 IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN article_like.id IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN article_like.article_id IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN article_like.user_id IS \'TRIAL\'');
        $this->addSql('ALTER TABLE experience ADD trial569 CHAR(1) DEFAULT NULL');
        $this->addSql('CREATE SEQUENCE experience_id_seq');
        $this->addSql('SELECT setval(\'experience_id_seq\', (SELECT MAX(id) FROM experience))');
        $this->addSql('ALTER TABLE experience ALTER id SET DEFAULT nextval(\'experience_id_seq\')');
        $this->addSql('COMMENT ON COLUMN experience.trial569 IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN experience.id IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN experience.user_id IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN experience.title IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN experience.content IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN experience.published_at IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN experience.filename IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN experience.updated_at IS \'TRIAL\'');
        $this->addSql('ALTER TABLE "user" ADD trial578 CHAR(1) DEFAULT NULL');
        $this->addSql('CREATE SEQUENCE user_id_seq');
        $this->addSql('SELECT setval(\'user_id_seq\', (SELECT MAX(id) FROM "user"))');
        $this->addSql('ALTER TABLE "user" ALTER id SET DEFAULT nextval(\'user_id_seq\')');
        $this->addSql('ALTER TABLE "user" ALTER user_connected TYPE SMALLINT');
        $this->addSql('ALTER TABLE "user" ALTER user_connected DROP DEFAULT');
        $this->addSql('ALTER TABLE "user" ALTER roles TYPE TEXT');
        $this->addSql('ALTER TABLE "user" ALTER roles DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN "user".trial578 IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN "user".id IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN "user".first_name IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN "user".last_name IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN "user".username IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN "user".email IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN "user".password IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN "user".telephone IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN "user".city IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN "user".zip_code IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN "user".user_connected IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN "user".created_at IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN "user".last_login_at IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN "user".roles IS \'TRIAL\'');
        $this->addSql('ALTER TABLE user_user_type ADD trial585 CHAR(1) DEFAULT NULL');
        $this->addSql('COMMENT ON COLUMN user_user_type.trial585 IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN user_user_type.user_id IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN user_user_type.user_type_id IS \'TRIAL\'');
        $this->addSql('ALTER TABLE article ADD trial543 CHAR(1) DEFAULT NULL');
        $this->addSql('CREATE SEQUENCE article_id_seq');
        $this->addSql('SELECT setval(\'article_id_seq\', (SELECT MAX(id) FROM article))');
        $this->addSql('ALTER TABLE article ALTER id SET DEFAULT nextval(\'article_id_seq\')');
        $this->addSql('COMMENT ON COLUMN article.trial543 IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN article.id IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN article.user_id IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN article.title IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN article.content IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN article.published_at IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN article.filename IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN article.updated_at IS \'TRIAL\'');
        $this->addSql('ALTER TABLE material ADD trial572 CHAR(1) DEFAULT NULL');
        $this->addSql('CREATE SEQUENCE material_id_seq');
        $this->addSql('SELECT setval(\'material_id_seq\', (SELECT MAX(id) FROM material))');
        $this->addSql('ALTER TABLE material ALTER id SET DEFAULT nextval(\'material_id_seq\')');
        $this->addSql('ALTER TABLE material ALTER availability TYPE SMALLINT');
        $this->addSql('ALTER TABLE material ALTER availability DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN material.trial572 IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN material.id IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN material.user_id IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN material.name IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN material.description IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN material.availability IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN material.created_on IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN material.filename IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN material.updated_at IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN material.borrowed_date IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN material.return_date IS \'TRIAL\'');
        $this->addSql('ALTER TABLE user_message ADD trial582 CHAR(1) DEFAULT NULL');
        $this->addSql('CREATE SEQUENCE user_message_id_seq');
        $this->addSql('SELECT setval(\'user_message_id_seq\', (SELECT MAX(id) FROM user_message))');
        $this->addSql('ALTER TABLE user_message ALTER id SET DEFAULT nextval(\'user_message_id_seq\')');
        $this->addSql('COMMENT ON COLUMN user_message.trial582 IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN user_message.id IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN user_message.id_message_sender_id IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN user_message.id_message_receiver_id IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN user_message.user_id IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN user_message.message IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN user_message.send_at IS \'TRIAL\'');
        $this->addSql('ALTER TABLE borrow_material ADD trial559 CHAR(1) DEFAULT NULL');
        $this->addSql('CREATE SEQUENCE borrow_material_id_seq');
        $this->addSql('SELECT setval(\'borrow_material_id_seq\', (SELECT MAX(id) FROM borrow_material))');
        $this->addSql('ALTER TABLE borrow_material ALTER id SET DEFAULT nextval(\'borrow_material_id_seq\')');
        $this->addSql('COMMENT ON COLUMN borrow_material.trial559 IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN borrow_material.id IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN borrow_material.id_borrower_id IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN borrow_material.id_lender_id IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN borrow_material.material_id IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN borrow_material.user_id IS \'TRIAL\'');
        $this->addSql('ALTER TABLE comment_experience ADD trial565 CHAR(1) DEFAULT NULL');
        $this->addSql('CREATE SEQUENCE comment_experience_id_seq');
        $this->addSql('SELECT setval(\'comment_experience_id_seq\', (SELECT MAX(id) FROM comment_experience))');
        $this->addSql('ALTER TABLE comment_experience ALTER id SET DEFAULT nextval(\'comment_experience_id_seq\')');
        $this->addSql('COMMENT ON COLUMN comment_experience.trial565 IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN comment_experience.id IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN comment_experience.author_name_id IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN comment_experience.experience_id IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN comment_experience.comment_content IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN comment_experience.commented_at IS \'TRIAL\'');
        $this->addSql('ALTER TABLE contact ADD trial565 CHAR(1) DEFAULT NULL');
        $this->addSql('CREATE SEQUENCE contact_id_seq');
        $this->addSql('SELECT setval(\'contact_id_seq\', (SELECT MAX(id) FROM contact))');
        $this->addSql('ALTER TABLE contact ALTER id SET DEFAULT nextval(\'contact_id_seq\')');
        $this->addSql('COMMENT ON COLUMN contact.trial565 IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN contact.id IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN contact.first_name IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN contact.last_name IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN contact.message IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN contact.email IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN contact.subject IS \'TRIAL\'');
        $this->addSql('ALTER TABLE material_borrower_message ADD trial575 CHAR(1) DEFAULT NULL');
        $this->addSql('CREATE SEQUENCE material_borrower_message_id_seq');
        $this->addSql('SELECT setval(\'material_borrower_message_id_seq\', (SELECT MAX(id) FROM material_borrower_message))');
        $this->addSql('ALTER TABLE material_borrower_message ALTER id SET DEFAULT nextval(\'material_borrower_message_id_seq\')');
        $this->addSql('COMMENT ON COLUMN material_borrower_message.trial575 IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN material_borrower_message.id IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN material_borrower_message.sender_message_id_id IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN material_borrower_message.receiver_message_id_id IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN material_borrower_message.user_id IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN material_borrower_message.message IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN material_borrower_message.send_at IS \'TRIAL\'');
        $this->addSql('ALTER TABLE experience_like ADD trial572 CHAR(1) DEFAULT NULL');
        $this->addSql('CREATE SEQUENCE experience_like_id_seq');
        $this->addSql('SELECT setval(\'experience_like_id_seq\', (SELECT MAX(id) FROM experience_like))');
        $this->addSql('ALTER TABLE experience_like ALTER id SET DEFAULT nextval(\'experience_like_id_seq\')');
        $this->addSql('COMMENT ON COLUMN experience_like.trial572 IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN experience_like.id IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN experience_like.experience_id IS \'TRIAL\'');
        $this->addSql('COMMENT ON COLUMN experience_like.user_id IS \'TRIAL\'');
    }
}
