<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGooZ9gM\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGooZ9gM/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGooZ9gM.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGooZ9gM\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerGooZ9gM\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'GooZ9gM',
    'container.build_id' => '85ad527b',
    'container.build_time' => 1600629936,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGooZ9gM');
