<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAWkyVNk\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAWkyVNk/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAWkyVNk.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAWkyVNk\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerAWkyVNk\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'AWkyVNk',
    'container.build_id' => 'b8a74735',
    'container.build_time' => 1607030848,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAWkyVNk');
